# Generated by Django 4.0.1 on 2022-02-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_publica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='publica',
            new_name='publicada',
        ),
    ]
